### ISSUE TITLE
Need to implement reads, salutes, and shares end-points

### ISSUE THREAD

**Issue by dustinWeaver** [topcoderinc/va-online-memorial-rest-api#2]
Currently none of the reads, salutes, or shares UI elements work due to their not being an endpoint on the API to handle these requests.  It should work as the following:

- Reads: Number increments when someone views the content
- Salutes: Number increments when someone "salutes" the content.  This functions much like Facebook's "like"
- Shares:  Number increments when someone shares content.

Related to [frontend issue 29](https://github.com/topcoderinc/va-online-memorial-frontend/issues/29)

**Comment by ksmacleod99** [comment]
fixed in PR #5
